[package]
name = "mqtt-async-subscriber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paho-mqtt = "0.12"
futures-util = "0.3.28"
dotenv = "0.15.0"
serde_json = "1.0.96"
serde = { version = "1.0", features = ["derive"] }
